import Sidebar from "@/components/SideBar";
import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { StoreProvider } from "../providers";
import UserProvider, { UserContext } from "../context/UserProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { cookies } from 'next/headers'
import { redirect } from "next/navigation";
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const res = await fetch("http://localhost:4000/api/user/check-auth", { headers: { token: cookies().get("Authorization")?.value } });

  const isAuthenticated = res.ok
  

  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider data={await res.json()}>
          <main className="font-sans bg-gray-100 h-screen flex">
            <Sidebar />
            {children}
          </main>
        </UserProvider>
      </body>
    </html>
  );
}
