import { useUser } from "@/app/context/UserProvider";
import ChatDetails from "@/components/ChatDetails";
import ChatService from "@/services/chatService";
import MessageService from "@/services/messageService";
import { Metadata } from "next";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";

import React from "react";
import { ImSpinner8 } from "react-icons/im";

export default async function page({ params }) {
  const chatId: string = params.id || "";
  const token = cookies()?.get("Authorization")?.value as string;
  const messageService = new MessageService(token);
  const chatService = new ChatService(token);

  try {
    const chatData = await chatService.getChatById(chatId);
    const messagesData = await messageService.getMessagesForChat(chatId);
    console.log(chatData, messagesData);
    return chatData && messagesData ? (
      <ChatDetails chatDetails={chatData} messagesData={messagesData} />
    ) : null;
    // <div className="flex justify-center items-center w-[80%]">
    //   <ImSpinner8 className=" animate-spin" size={100} />
    // </div>
  } catch (error) {
    redirect("/auth/login");
  }
}
export const metadata: Metadata = {
  title: "Chat Room",
  description: "Generated by create next app",
};
